### ISSUE TITLE
License? Are these redistributable?

### ISSUE THREAD

**Issue by dtzWill** [avast-tl/retdec-support#1]
I'm mostly interested in the answer to this:

**Can I re-host the contents of these archives, in whole or in part, freely?**

Use-case: Packaging retdec for distribution in NixOS, is it okay for us to host this content?
(this is often prohibited for proprietary software and resources)

Licenses also clarify rights granted as much as restrict use... sometimes promising the content is yours to share or that you promise not to sue folks using it O:).

Please consider specifying licensing details so we can provide retdec to users with these parts included!

**Comment by s3rvac** [comment]
Thank you for noticing! This is an omission on our part. We will add the missing licensing details.

**Comment by PeterMatula** [comment]
Added MIT license.
